export { default as Dashboard } from './Dashboard';
export { default as Kanban } from './Kanban';
export { default as Profile } from './Profile';
export { default as Employees } from './Employees';
export { default as Chatbot } from './Chatbot';
export { default as Progress } from './Progress';
export { default as Editor } from './Editor';
export { default as Helpdesk } from './Helpdesk';
export { default as ColorPicker } from './ColorPicker';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';

